### ISSUE TITLE
两个交互问题

### ISSUE THREAD

**Issue by wufuxi** [ustbhuangyi/vue-sell#1]
大神，研究了下你的demo，有两个小问题。
1、当“特色粥品”，也就是最后一类菜只有一个菜品的时候，点击这个分类，不会有点击后效果。
2、滚动菜品，分类不会同步滚动。就是当分类很多，有些分类需要滚动才能看到时，如果你滚动右边的菜品，滚动到遮住的分类时，分类不会自动滚动到可视区。

**Comment by ustbhuangyi** [comment]
恩，这块都是可以做优化的，欢迎提 pr~
