### ISSUE TITLE
mixin文件引入问题

### ISSUE THREAD

**Issue by Alvin1992** [ustbhuangyi/vue-sell#18]
+ 在 `index.style` 中引入了 `mixin.styl` 为什么在每个组件中还需要再引入一次？
+ 全局引入了 `index.styl` 不就意味着已经引入了 `mixin` 中的代码了吗？
+ 我把组件单独引入的 `mixin` 注释掉就会报错，这是为什么？

我上面的理解是不是哪里错了？还请老师答复

**Comment by ustbhuangyi** [comment]
需要组件单独引入，mixin实际上就是把引用的mixin定义的代码替换到引入的位置，从stylus的编译考虑，如果你使用了某个mixin定义的代码而不去指定它引用的路径，那么它是完全不知道从哪去查找这个mixin定义的

**Comment by yxuecheng** [comment]
m
