### ISSUE TITLE
小球动画的问题

### ISSUE THREAD

**Issue by TerrenceFong** [ustbhuangyi/vue-sell#2]
你好，我在研究小球动画源码的时候在想`cartcontrol`和`shopcart`这两个组件是不是可以理解为是平行组件之前的通信？
既是`cartcontrol`把`<div class="cart-add icon-add_circle" @click.stop.prevent="addCart"></div>`传入到`shopcart`中，可以这样理解吗？

**Comment by ustbhuangyi** [comment]
事件通讯是一种解决方案，更好的方式是通过 Vuex 实现~
