### ISSUE TITLE
关于图片的适配

### ISSUE THREAD

**Issue by xzfd1010** [ustbhuangyi/vue-sell#21]
你好，看到这个项目里面img标签里面的图片，都是2x图，请问在iphone 6sp下是不是应该适配3x图，如果是实际项目中，是服务器会根据屏幕的dpr来返回不同尺寸的图片么，还是说2x图就已经足够了？

**Comment by ustbhuangyi** [comment]
看你对图片的质量要求了。当然也可以根据当前手机的 dpr 去请求不同的 2x 和 3x 图片。
