### ISSUE TITLE
多次来回切换首页和商品详情页会出现addFood方法被执行多次，点击添加增加的次数是来回切换的次数

### ISSUE THREAD

**Issue by IFmiss** [ustbhuangyi/vue-sell#25]
food.vue文件下中的addFood方法，第一次进入点击添加商品会增加 1 ，但是再返回首页再进入商品详情页的话点击添加商品则会增加 2 ，addFood被执行了两次 ， 之后岁来回切换的数量，增量也会递增。请问你有没有遇到学生是这种问题的！怎么解决啊！

**Comment by yumengzhong** [comment]
`   if (!this.scroll) {
       this.scroll = new BScroll(this.$refs.food, {
           click: true
       });
     } else {
        this.scroll.refresh();
      }`

请问在实例化better-scroll组件时   this.scroll中scroll不用在data里声明么
