### ISSUE TITLE
用vue-cli搭建的饿了么app项目，提交到github上，用 github pages 打不开网页，怎么办？

### ISSUE THREAD

**Issue by bxm0927** [ustbhuangyi/vue-sell#29]
我想做一个 github page 的项目演示地址，和老师的  http://vuejssellapp.t.imooc.io/#!/ 一样，可是我的 /api/seller 请求不到，老师怎么解决呢？

**Comment by ustbhuangyi** [comment]
数据写死在前端即可

**Comment by bxm0927** [comment]
具体怎么做呢老师？这是我的演示页：https://bxm0927.github.io/elelmeApp/dist/?id=123#/goods，数据请求失败404
