### ISSUE TITLE
上传github演示问题

### ISSUE THREAD

**Issue by biou23** [ustbhuangyi/vue-sell#5]
准备写进简历里面，因为是node模拟的数据，不知道怎么才能像老师一样，弄的可以直接给别人观看

**Comment by wuzhixian1016** [comment]
你把打包后的代码放到GitHub pages应该就可以看到了

**Comment by biou23** [comment]
不是要用node启动prod.server.js才行吗，打包后的代码直接打开没数据啊

**Comment by ustbhuangyi** [comment]
2种思路，一是可以买个阿里云主机或者vps，然后搭个 node 服务，有对外访问的地址即可，二是可以把模拟的数据写死在前端代码里，不需要从服务端获取。

**Comment by konglingwen94** [comment]
这里有一个实现`Api`部署的思路--[https://github.com/konglingwen94/vue-sell/blob/master/src/api/index.js](https://github.com/konglingwen94/vue-sell/blob/master/src/api/index.js)
