### ISSUE TITLE
foodlist页面长按拖动的问题

### ISSUE THREAD

**Issue by guangnaoke** [ustbhuangyi/vue-sell#7]
foodlist商品栏 better-scroll 插件 probeType: 3 设置为3长按拖动会出现卡屏 设置为1的话 画面顺畅 但是左边的menulist点击和匹配foodlist页面的item栏的时候 背景白色出现会有问题. ios的卡屏现象严重一点, 安卓的稍微好点

**Comment by ustbhuangyi** [comment]
请问你的手机型号，操作系统是怎样的

**Comment by guangnaoke** [comment]
iphone 6 系统是最新的

**Comment by ustbhuangyi** [comment]
我们这没有复现，怀疑你是省电模式？
